name: build
on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    # Once a month
    - cron: '0 0 1 * *'
  workflow_dispatch:

jobs:
  build_and_test:
    name: pybind11_json_vendor
    uses: open-rmf/rmf_ci_templates/.github/workflows/reusable_build.yaml@main
    with:
      # NOTE: Avoid adding comments in the packages lines, this can break some of the called scripts in github actions
      packages: |
        pybind11_json_vendor